-- Create the COUNTRY table
CREATE TABLE COUNTRY (
    id NUMBER PRIMARY KEY,
    institute INTEGER,
    name VARCHAR2(100)
);
-- Insert 10 records into the COUNTRY table
INSERT INTO COUNTRY (id, institute, name) VALUES (1, 0, 'India');
INSERT INTO COUNTRY (id, institute, name) VALUES (2, 0, 'Pakistan');
INSERT INTO COUNTRY (id, institute, name) VALUES (3, 0, 'Sri Lanka');
INSERT INTO COUNTRY (id, institute, name) VALUES (4, 0, 'Iran');
INSERT INTO COUNTRY (id, institute, name) VALUES (5, 0, 'Iraq');
INSERT INTO COUNTRY (id, institute, name) VALUES (6, 0, 'Bhutan');
INSERT INTO COUNTRY (id, institute, name) VALUES (7, 0, 'Nepal');
INSERT INTO COUNTRY (id, institute, name) VALUES (8, 0, 'Afghanistan');
INSERT INTO COUNTRY (id, institute, name) VALUES (9, 0, 'Bangladesh');
INSERT INTO COUNTRY (id, institute, name) VALUES (10, 0, 'Maldives');



-- Create the STATE table
CREATE TABLE STATE (
    ID NUMBER PRIMARY KEY,
    INSTITUTE INTEGER,
    NAME VARCHAR2(100)
);

-- Insert records for Indian states and territories
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (1, 1, 'Andhra Pradesh');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (2, 1, 'Arunachal Pradesh');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (3, 1, 'Assam');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (4, 1, 'Bihar');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (5, 1, 'Chhattisgarh');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (6, 1, 'Goa');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (7, 1, 'Gujarat');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (8, 1, 'Haryana');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (9, 1, 'Himachal Pradesh');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (10, 1, 'Jharkhand');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (11, 1, 'Karnataka');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (12, 1, 'Kerala');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (13, 1, 'Madhya Pradesh');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (14, 1, 'Maharashtra');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (15, 1, 'Manipur');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (16, 1, 'Meghalaya');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (17, 1, 'Mizoram');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (18, 1, 'Nagaland');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (19, 1, 'Odisha');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (20, 1, 'Punjab');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (21, 1, 'Rajasthan');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (22, 1, 'Sikkim');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (23, 1, 'Tamil Nadu');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (24, 1, 'Telangana');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (25, 1, 'Tripura');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (26, 1, 'Uttar Pradesh');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (27, 1, 'Uttarakhand');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (28, 1, 'West Bengal');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (29, 1, 'Andaman and Nicobar Islands');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (30, 1, 'Chandigarh');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (31, 1, 'Dadra and Nagar Haveli and Daman and Diu');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (32, 1, 'Lakshadweep');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (33, 1, 'Delhi');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (34, 1, 'Puducherry');
-- Include Jammu and Kashmir and Ladakh
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (35, 1, 'Jammu and Kashmir');
INSERT INTO STATE (ID, INSTITUTE, NAME) VALUES (36, 1, 'Ladakh');



-- Create the CITY table
CREATE TABLE CITY (
    ID NUMBER PRIMARY KEY,
    INSTITUTE INTEGER,
    NAME VARCHAR2(100)
);

-- Insert records for all districts in Madhya Pradesh
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (1, 13, 'Bhopal');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (2, 13, 'Indore');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (3, 13, 'Jabalpur');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (4, 13, 'Gwalior');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (5, 13, 'Ujjain');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (6, 13, 'Sagar');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (7, 13, 'Rewa');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (8, 13, 'Satna');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (9, 13, 'Katni');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (10, 13, 'Chhindwara');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (11, 13, 'Guna');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (12, 13, 'Shivpuri');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (13, 13, 'Vidisha');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (14, 13, 'Damoh');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (15, 13, 'Mandsaur');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (16, 13, 'Ratlam');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (17, 13, 'Neemuch');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (18, 13, 'Dewas');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (19, 13, 'Khargone');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (20, 13, 'Khandwa');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (21, 13, 'Burhanpur');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (22, 13, 'Harda');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (23, 13, 'Hoshangabad');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (24, 13, 'Sehore');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (25, 13, 'Betul');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (26, 13, 'Narsinghpur');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (27, 13, 'Raisen');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (28, 13, 'Shajapur');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (29, 13, 'Agar Malwa');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (30, 13, 'Alirajpur');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (31, 13, 'Anuppur');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (32, 13, 'Ashoknagar');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (33, 13, 'Balaghat');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (34, 13, 'Barwani');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (35, 13, 'Bhind');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (36, 13, 'Chhatarpur');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (37, 13, 'Dhar');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (38, 13, 'Dindori');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (39, 13, 'Guna');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (40, 13, 'Harda');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (41, 13, 'Hoshangabad');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (42, 13, 'Jhabua');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (43, 13, 'Katni');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (44, 13, 'Khandwa');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (45, 13, 'Khargone');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (46, 13, 'Mandla');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (47, 13, 'Mandsaur');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (48, 13, 'Morena');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (49, 13, 'Narsinghpur');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (50, 13, 'Neemuch');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (51, 13, 'Panna');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (52, 13, 'Raisen');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (53, 13, 'Ratlam');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (54, 13, 'Rewa');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (55, 13, 'Sagar');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (56, 13, 'Satna');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (57, 13, 'Sehore');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (58, 13, 'Seoni');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (59, 13, 'Shahdol');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (60, 13, 'Shajapur');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (61, 13, 'Sheopur');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (62, 13, 'Shivpuri');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (63, 13, 'Sidhi');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (64, 13, 'Singrauli');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (65, 13, 'Tikamgarh');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (66, 13, 'Ujjain');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (67, 13, 'Umaria');
INSERT INTO CITY (ID, INSTITUTE, NAME) VALUES (68, 13, 'Vidisha');
-- Add more districts as needed


-- Create the VILLAGE table
CREATE TABLE VILLAGE (
    ID NUMBER PRIMARY KEY,
    INSTITUTE INTEGER,
    NAME VARCHAR2(100)
);

-- Insert records for all local bodies with unique IDs and INSTITUTE set to 1
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (1, 1, 'ACHARPURA');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (2, 1, 'ADAMPUR CHAWANI');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (3, 1, 'AGARIYA');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (4, 1, 'AMJHARA');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (5, 1, 'AMLA');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (6, 1, 'AMONI');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (7, 1, 'AMRAVAT KALAN');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (8, 1, 'ARWALIYA');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (9, 1, 'BADJHIRI');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (10, 1, 'BAGONIYA');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (11, 1, 'BAGRODA');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (12, 1, 'BAKANIYA');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (13, 1, 'BALAMPUR');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (14, 1, 'BANGRASIA');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (15, 1, 'BARKHEDA BONDAR');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (16, 1, 'BARKHEDA NATHU');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (17, 1, 'BARKHEDA SALAM');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (18, 1, 'BARKHEDI ABDULLA');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (19, 1, 'BERKHEDI BAZYAFT');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (20, 1, 'BHANPUR');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (21, 1, 'BILKHIRIYA KALA');
-- Continue inserting records for the remaining local bodies



-- Insert records for villages with unique IDs starting from 22 and INSTITUTE set to 21
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (22, 21, 'Adagaon');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (23, 21, 'Ahukhana');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (24, 21, 'Andhari');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (25, 21, 'Bada Buzurg');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (26, 21, 'Badgaon Mafi');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (27, 21, 'Badi');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (28, 21, 'Badjhiri');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (29, 21, 'Badkheda');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (30, 21, 'Badsingi');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (31, 21, 'Bahadarpur');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (32, 21, 'Bakhari');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (33, 21, 'Bambhada');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (34, 21, 'Baroli');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (35, 21, 'Basali');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (36, 21, 'Bhawasa');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (37, 21, 'Bhota');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (38, 21, 'Boharda');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (39, 21, 'Borgaonkhurd');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (40, 21, 'Borsar');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (41, 21, 'Chandgarh');
-- Continue inserting records for the remaining villages
/

-- Insert records for villages with unique IDs starting from 42 and INSTITUTE set to 2
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (42, 2, 'Pradesh');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (43, 2, 'Ambamolya');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (44, 2, 'Ankya');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (45, 2, 'Arandia');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (46, 2, 'Aranya');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (47, 2, 'Asakhedi');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (48, 2, 'Asrawad Buzurg');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (49, 2, 'Asrawad Khurd');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (50, 2, 'Badia Hat');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (51, 2, 'Badia Keema');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (52, 2, 'Balya Kheda');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (53, 2, 'Bangarda Bada');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (54, 2, 'Baroda Daulat');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (55, 2, 'Baroda Kara');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (56, 2, 'Bawalya Buzurg');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (57, 2, 'Bawalya Khurd');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (58, 2, 'Begam Khedi');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (59, 2, 'Berchha');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (60, 2, 'Bhicholi Hapsi');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (61, 2, 'Bhicholi Mardana');
-- Continue inserting records for the remaining villages


-- Insert records for villages with unique IDs starting from 62 and INSTITUTE set to 3
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (62, 3, 'Akola');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (63, 3, 'Amahinota');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (64, 3, 'Amakhoh');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (65, 3, 'Amanala');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (66, 3, 'Andhuwa');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (67, 3, 'Atha Kheda');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (68, 3, 'Badera Kalan');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (69, 3, 'Badhaiya Kheda');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (70, 3, 'Badkhera');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (71, 3, 'Badkheri');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (72, 3, 'Bagheli');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (73, 3, 'Baghoda');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (74, 3, 'Baghodi');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (75, 3, 'Bahdan');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (76, 3, 'Bahoripar');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (77, 3, 'Balhwara');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (78, 3, 'Bamhani');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (79, 3, 'Bamhnoda');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (80, 3, 'Bamhnodi');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (81, 3, 'Bamhori');
-- Continue inserting records for the remaining villages

-- Insert records for villages with unique IDs starting from 82 and INSTITUTE set to 4
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (82, 4, 'Adupura Khalsa');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (83, 4, 'Adupurajagir');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (84, 4, 'Agrabhatpura');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (85, 4, 'Ajaypur');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (86, 4, 'Akbarpur');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (87, 4, 'Alinagar');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (88, 4, 'Amai');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (89, 4, 'Amargarh');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (90, 4, 'Antri');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (91, 4, 'Ari');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (92, 4, 'Aroli');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (93, 4, 'Aron');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (94, 4, 'Arora');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (95, 4, 'Arroli');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (96, 4, 'Badagaon');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (97, 4, 'Badagaonjagir');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (98, 4, 'Baderafutkar');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (99, 4, 'Badkagaon');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (100, 4, 'Badori');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (101, 4, 'Bagwalagaon');
-- Continue inserting records for the remaining villages


-- Insert records for villages with unique IDs starting from 102 and INSTITUTE set to 5
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (102, 5, 'Ajrana');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (103, 5, 'Akasoda');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (104, 5, 'Alampur (Udana)');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (105, 5, 'Amirpur Kuslakhedi');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (106, 5, 'Amirpur (Fajalpur)');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (107, 5, 'Aslana');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (108, 5, 'Badalkhedi');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (109, 5, 'Badarkha Berasiya');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (110, 5, 'Badhkummed');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (111, 5, 'Badodiya Bhand');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (112, 5, 'Bakaniya');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (113, 5, 'Bamora');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (114, 5, 'Banskhedi Khalsa');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (115, 5, 'Bhainsoda');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (116, 5, 'Bhanwri');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (117, 5, 'Biaora');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (118, 5, 'Bodani');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (119, 5, 'Bolasa');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (120, 5, 'Brijrajkhedi');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (121, 5, 'Chakjai Rampur');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (122, 5, 'Chandesara');
-- Continue inserting records for the remaining villages

-- Insert records for villages with unique IDs starting from 123 and INSTITUTE set to 6
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (123, 6, 'Agariya');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (124, 6, 'Agra');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (125, 6, 'Ama Khurd');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (126, 6, 'Amaoni');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (127, 6, 'Amet');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (128, 6, 'Amoda');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (129, 6, 'Apchand');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (130, 6, 'Arjani');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (131, 6, 'Bachhlon');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (132, 6, 'Badarchuwa');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (133, 6, 'Badaua');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (134, 6, 'Badbadi');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (135, 6, 'Badera');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (136, 6, 'Badkuwan');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (137, 6, 'Badona');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (138, 6, 'Badora');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (139, 6, 'Badtuma');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (140, 6, 'Baheria Gadgad');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (141, 6, 'Baheriya Sahni');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (142, 6, 'Bakhra');
INSERT INTO VILLAGE (ID, INSTITUTE, NAME) VALUES (143, 6, 'Bakswaha');
-- Continue inserting records for the remaining villages

